exp_num: 1
do_wandb: False
do_validation: False
base_ds: '/data/raktim/Datasets/Oxford-Radar/'
pickle_loc: 'src/utils/robotcar_1.pkl'
val_pickle_loc: 'src/utils/robotcar_10.pkl'
feat_extractor_model_path: 'src/checkpoints/SALSA/Model/feat_extractor.pth'
regressor:
  num_mixer_channels: 1
  pose_regressor_layers: 6
  global_desc_dim_scale: 2
num_clusters: 1000
loss:
  contrastive_loss_name: 'triplet_loss'  # 'triplet_loss' or 'barlow_loss'
  pose_loss_rot_weight: 100 
  contrastive_loss_scale: 100 # 100 for triplet_loss, 0.0001 for barlow_loss

training:
  batch_size: 1024
  epochs: 400
  max_lr: 0.01
  pct_start: 0.1
  final_div_factor: 100000
  save_folder: 'src/checkpoints/FlashMix'

